version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/tty:/dev/tty # Changez cela selon votre clé USB Zigbee
    depends_on:
      - mosquitto
    restart: always
  
  publisher:
    build:
      context: .
      dockerfile: Dockerfile-publisher
    environment:
      - MQTT_BROKER=mosquitto
    depends_on:
      - mosquitto

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile-subscriber
    environment:
      - MQTT_BROKER=mosquitto
      - HTTP_ENDPOINT=http://backend:5000/api/temperature
    depends_on:
      - mosquitto
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
