homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1883
serial:
  port: /dev/ttyUSB0
advanced:
  network_key:
    - 150
    - 127
    - 125
    - 190
    - 52
    - 4
    - 223
    - 226
    - 181
    - 116
    - 93
    - 45
    - 15
    - 99
    - 227
    - 193
  pan_id: 52376
  ext_pan_id:
    - 233
    - 126
    - 144
    - 234
    - 188
    - 212
    - 31
    - 7
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xf0f5bdfffe2d1ea8':
    friendly_name: '0xf0f5bdfffe2d1ea8'
  '0x543204fffe335684':
    friendly_name: '0x543204fffe335684'
  '0x543204fffe3350b4':
    friendly_name: '0x543204fffe3350b4'
